{
    "files.autoSave": "onFocusChange",
    "editor.fontFamily": "SF Mono",
    "editor.fontWeight": "600",
    "editor.fontSize": 14,
    "editor.cursorStyle": "line",
    "terminal.integrated.fontFamily": "SF Mono",
    "terminal.integrated.fontSize": 13,
    "editor.tabSize": 2,
    "terminal.integrated.fontLigatures": true,
    "editor.fontLigatures": true,
    "window.reopenFolders": "one",
    "window.restoreFullscreen": false,
    "window.zoomLevel": 0,
    "update.channel": "default",
    "C_Cpp.clang_format_path": null,
    "C_Cpp.clang_format_style": "Google",
    "C_Cpp.clang_format_fallbackStyle": "Visual Studio",
    "C_Cpp.clang_format_sortIncludes": null,
    "C_Cpp.clang_format_formatOnSave": false,
    "C_Cpp.autocomplete": "Default",
    "javascript.validate.enable": false,
    "workbench.activityBar.visible": true,
    "workbench.sideBar.location": "right",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.statusBar.visible": true,
    "terminal.external.osxExec": "iTerm.app",
    "vsicons.presets.jsOfficial": true,
    "workbench.editor.enablePreview": false,
    "gitProjectManager.baseProjectsFolders": [
        "/Users/siddiqui/Documents/Projects/"
    ],
    "typescript.check.tscVersion": false,
    "workbench.welcome.enabled": false,
    "editor.minimap.enabled": true,
    "editor.minimap.maxColumn": 120,
    "editor.minimap.renderCharacters": false,
    "cSpell.userWords": [
        "Allterrain",
        "Cyclocross",
        "Fullscreen",
        "Listnride",
        "Pedelec",
        "Roadbike",
        "Tfidf",
        "Trecking",
        "Voor",
        "backend",
        "biketitle",
        "biketype",
        "coef",
        "covariance",
        "dropdown",
        "enmacc",
        "envs",
        "hough",
        "imshow",
        "infobars",
        "kalman",
        "kmeans",
        "matplotlib",
        "minification",
        "minified",
        "minimap",
        "momentjs",
        "ngram",
        "nltk",
        "numpy",
        "params",
        "prjdir",
        "pycache",
        "pylint",
        "pyplot",
        "rescale",
        "rescaled",
        "responsivity",
        "siddiqui",
        "signup",
        "sklearn",
        "sobel",
        "stdafx",
        "toarray",
        "uglifyjs",
        "uuml",
        "vectorizer",
        "vsicons",
        "xlabel",
        "ylabel"
    ],
    "python.pythonPath": "/Users/siddiqui/miniconda3/envs/carnd-term1/bin/python",
    "python.linting.pylintCategorySeverity.convention": "Information",
    "python.autoComplete.preloadModules": [
        "numpy",
        "tensorflow"
    ],
    "python.linting.pylintArgs": [
        "--errors-only"
    ],
    "zenMode.hideTabs": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/*.pyc": true,
        ".vscode": true,
        ".idea": true,
        "**/__pycache__": true
    },
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "code-runner.executorMap": {
        "python": "/Users/siddiqui/miniconda3/envs/carnd-term1/bin/python"
    },
    "code-runner.clearPreviousOutput": true,
    "code-runner.runInTerminal": true,
    "vsicons.projectDetection.autoReload": true,
    "editor.formatOnSave": false,
    "C_Cpp.intelliSenseEngine": "Default",
    "workbench.editor.tabCloseButton": "left",
    "editor.renderIndentGuides": false,
    "editor.wordWrap": "off",
    "gitlens.diffWithBranch": false,
    "gitlens.codeLens.enabled": false,
    "gitlens.annotations.file.recentChanges.hover.details": false,
    "gitlens.advanced.menus": {
        "editorContext": {
            "blame": false,
            "copy": false,
            "details": false,
            "fileDiff": false,
            "history": false,
            "lineDiff": false,
            "remote": false
        },
        "editorTitle": {
            "blame": false,
            "fileDiff": false,
            "history": false,
            "remote": false,
            "status": false
        },
        "editorTitleContext": {
            "blame": false,
            "fileDiff": false,
            "history": false,
            "remote": false
        },
        "explorerContext": {
            "fileDiff": false,
            "history": false,
            "remote": false
        }
    },
    "window.titleBarStyle": "custom",
    "window.nativeTabs": false,
    "editor.cursorBlinking": "solid",
    "workbench.panel.location": "right",
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": true,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": true,
        "suppressWelcomeNotice": true
    },
    "workbench.colorTheme": "Xcode_default"
}